"""The determinism contract.

If these fail, nothing downstream can be trusted: the eval harness compares a
detector run against ground truth generated by a previous run, and a generator
that drifts between invocations makes every recall figure meaningless.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

import numpy as np
from datagen.config import CHUNK_ROWS, TABLE_NAMES, ScaleConfig
from datagen.pipeline import generate
from datagen.rng import StreamRegistry, weighted_index

SEED = 42
SLICE_EMPLOYEES = 1000


def build_cfg(policy, out, seed: int = SEED, employees: int = SLICE_EMPLOYEES):
    return ScaleConfig.build("10k", seed, policy.population, out=out, employees=employees)


def _digest(root: Path) -> dict[str, str]:
    return {
        str(path.relative_to(root)).replace("\\", "/"): hashlib.sha256(
            path.read_bytes()
        ).hexdigest()
        for path in sorted(root.rglob("*.parquet"))
    }


def test_same_seed_is_byte_identical(tmp_path, policy):
    first, second = tmp_path / "a", tmp_path / "b"
    generate(build_cfg(policy, first), policy)
    generate(build_cfg(policy, second), policy)
    left, right = _digest(first), _digest(second)
    assert left, "no parquet written"
    assert left == right


def test_different_seed_changes_the_data(tmp_path, policy):
    first, second = tmp_path / "a", tmp_path / "b"
    generate(build_cfg(policy, first, seed=SEED), policy)
    generate(build_cfg(policy, second, seed=SEED + 1), policy)
    assert _digest(first) != _digest(second)


def test_table_streams_are_independent():
    """Adding or reordering one table must not move another table's numbers."""
    streams = StreamRegistry(SEED)
    a = streams.table("employee_master").field("grade").random(5)
    b = streams.table("dim_job").field("grade").random(5)
    assert not np.allclose(a, b)
    # Re-deriving the same stream gives the same values, in any order.
    again = StreamRegistry(SEED)
    assert np.allclose(again.table("dim_job").field("grade").random(5), b)
    assert np.allclose(again.table("employee_master").field("grade").random(5), a)


def test_field_streams_are_named_not_ordered():
    """Field streams are keyed by name, so adding a column shifts nothing."""
    table = StreamRegistry(SEED).table("employee_master")
    assert not np.allclose(table.field("grade").random(4), table.field("tenure").random(4))
    assert np.allclose(
        table.field("grade", chunk=0).random(4), table.field("grade", chunk=0).random(4)
    )
    assert not np.allclose(
        table.field("grade", chunk=0).random(4), table.field("grade", chunk=1).random(4)
    )


def test_draws_are_prefix_stable():
    """The first n of an m-row draw equal the first n of an n-row draw.

    This is what lets a small slice be a genuine prefix of a large run rather
    than a different population that happens to be the same size.
    """
    weights = np.array([3.0, 1.0, 2.0, 5.0])
    long = weighted_index(StreamRegistry(SEED).table("employee_master").field("site"),
                          weights, 500)
    short = weighted_index(StreamRegistry(SEED).table("employee_master").field("site"),
                           weights, 50)
    assert list(long[:50]) == list(short)


def test_chunk_boundaries_do_not_move_with_scale(policy):
    """Chunk size is a constant, so row N lands in the same chunk at any tier."""
    small = ScaleConfig.build("10k", SEED, policy.population)
    large = ScaleConfig.build("1m", SEED, policy.population)
    assert next(iter(small.chunks()))[:2] == next(iter(large.chunks()))[:2]
    assert small.chunk_count == 1
    assert large.chunk_count == large.employees // CHUNK_ROWS


def test_every_written_table_has_a_stream():
    """A table generated without its own stream would ride on another's."""
    from datagen.schemas import SCHEMAS

    assert set(SCHEMAS) == set(TABLE_NAMES)
