"""Layer 2: for each code, the injector and the detector must agree.

Parametrised over `policy/peer_stats.yaml` rather than written out twelve
times, exactly as the layer-1 suite is parametrised over the rule pack: adding
a detector adds its test, and a detector that finds nothing fails here instead
of showing up as a quiet 0% row in the eval report weeks later.

The recall bar is 100% at 10k rather than the spec's 85%, on purpose. Every
code is injected at least five times, and a detector that misses one of five is
not a threshold away from working -- it means the injector and the detector
disagree about what the code means. 85% is the promise made about the family
against real data; this is the regression guard against ourselves.
"""

from __future__ import annotations

import json

import pytest
from detector.layers.l2_peer import (
    DETECTORS,
    PEER_FIELDS,
    REQUIRED_COLUMNS,
    cohort_key_sql,
    run_peer,
)
from detector.layers.l2_salary import additive_gap

pytestmark = pytest.mark.usefixtures("features")

CODES = sorted(DETECTORS)

# Terms a reviewer would need a data-science background to read. The evidence
# bundle is user-facing (CLAUDE.md), so this is the same list the phase gate
# enforces, kept here so a new template cannot slip one in between gate runs.
JARGON = (
    "z-score", "robust z", "sigma", "isolation forest", "autoencoder",
    "reconstruction", "residual", "shap", "percentile", "outlier", "cusum",
)


@pytest.fixture(scope="module")
def truth(labels_con):
    """Ground truth as `{code: {employee_id: (from, to)}}`. Tests only."""
    rows = labels_con.execute(
        "SELECT anomaly_code, employee_id, min(period_from), max(period_to) "
        "FROM labels_anomaly GROUP BY 1, 2"
    ).fetchall()
    out: dict[str, dict[str, tuple[int, int]]] = {}
    for code, employee, start, end in rows:
        out.setdefault(code, {})[employee] = (int(start), int(end))
    return out


@pytest.fixture(scope="module")
def found(l2):
    out: dict[str, dict[str, tuple[int, int]]] = {}
    for hit in l2.hits:
        out.setdefault(hit["anomaly_code"], {})[hit["employee_id"]] = (
            hit["period_from"], hit["period_to"]
        )
    return out


@pytest.fixture(scope="module")
def confounders(labels_con):
    rows = labels_con.execute(
        "SELECT employee_id, confounder_type, confounds_code FROM labels_confounder"
    ).fetchall()
    return {r[0]: (r[1], r[2]) for r in rows}


# --------------------------------------------------------------------- codes


@pytest.mark.parametrize("code", CODES)
def test_every_code_is_injected(code, truth):
    """A detector for a code nothing injects cannot be scored at all."""
    assert truth.get(code), f"{code} has a detector but no injected instances"


@pytest.mark.parametrize("code", CODES)
def test_detector_finds_every_injected_case(code, truth, found):
    missed = sorted(set(truth[code]) - set(found.get(code, {})))
    assert not missed, (
        f"{code}: {len(missed)} injected employees not found ({missed[:5]}); "
        "reconcile the injector and the detector in docs/ANOMALY_CATALOG.md "
        "before touching a threshold"
    )


@pytest.mark.parametrize("code", CODES)
def test_detector_dates_the_window(code, truth, found):
    """A finding must overlap the months the injector actually touched."""
    for employee, (start, end) in truth[code].items():
        got = found[code][employee]
        assert got[0] <= end and got[1] >= start, (
            f"{code}/{employee}: detected {got}, injected ({start}, {end})"
        )


@pytest.mark.parametrize("code", CODES)
def test_precision_is_reasonable(code, truth, found):
    """A statistic is not a fact, but three quarters of a queue must be real."""
    hits = found.get(code, {})
    correct = len(set(hits) & set(truth[code]))
    assert correct / len(hits) >= 0.75, (
        f"{code}: {len(hits) - correct} of {len(hits)} findings are not "
        "accounted for by ground truth"
    )


def test_confounders_are_not_flagged_by_their_own_code(l2, confounders):
    """The planted legitimate look-alikes are the precision test that matters."""
    fell_for = [
        (hit["employee_id"], hit["anomaly_code"], confounders[hit["employee_id"]][0])
        for hit in l2.hits
        if hit["employee_id"] in confounders
        and hit["anomaly_code"] == confounders[hit["employee_id"]][1]
    ]
    assert not fell_for, f"confounders flagged by the code they test: {fell_for}"


# ------------------------------------------------------------------ cohorts


def test_cohort_key_matches_the_feature_build(con, policy):
    """The detector's key must be byte-identical to `cohort_stats`'s.

    They are generated by two different modules from one ladder, and a single
    character of difference means every join misses and every peer comparison
    silently disappears.
    """
    for dims in policy.cohort_ladder:
        built = con.execute(
            f"SELECT {cohort_key_sql(dims)} FROM features_employee LIMIT 1"
        ).fetchone()[0]
        known = con.execute(
            "SELECT count(*) FROM cohort_stats WHERE cohort_key = ? "
            "AND cohort_dims = ?",
            [built, "|".join(dims)],
        ).fetchone()[0]
        assert known, f"key {built!r} at level {dims} matches no cohort"


def test_every_employee_gets_a_cohort(l2, cfg):
    assert sum(l2.cohorts.by_level.values()) == cfg.employees


def test_small_cohorts_are_on_the_last_rung_only(l2):
    """Falling short of `min_size` is allowed only where there is no rung left."""
    last = l2.cohorts.by_level.get(len(l2.cohorts.levels), 0)
    assert l2.cohorts.below_min <= last


def test_the_ladder_is_not_carrying_the_whole_population(l2):
    assert l2.cohorts.last_rung_share < 0.30


# -------------------------------------------------------------- the model


def test_expected_salary_model_is_fitted(l2, cfg):
    assert l2.salary is not None and l2.salary.rows == cfg.employees


def test_attributions_reconstruct_the_prediction(l2):
    """`baseline + every driver's share = expected pay`, to the riyal."""
    assert additive_gap(l2.salary) <= 1.0


def test_model_reads_only_legitimate_drivers(l2, policy):
    """Nothing derived from pay itself, and certainly nothing from the labels."""
    assert set(l2.salary.drivers) == set(policy.expected_salary["drivers"])
    assert not [d for d in l2.salary.drivers
                if "salary" in d or "pay" in d or "allowance" in d]


# ------------------------------------------------------------- the findings


def test_every_finding_has_the_columns_the_emitter_needs(l2):
    for hit in l2.hits:
        assert hit["employee_id"] and hit["anomaly_code"]
        assert hit["period_from"] <= hit["period_to"]
        assert hit["months_flagged"] >= 1
        assert hit["financial_impact_monthly"] >= 0
        assert hit["financial_impact_cumulative"] >= 0
        assert hit["description"] and hit["recommended_actions"]


def test_required_columns_are_declared():
    """The contract the detectors are validated against, not a free-form dict."""
    assert set(REQUIRED_COLUMNS) >= {
        "employee_id", "first_period_paid", "last_period_paid", "months_paid",
        "monthly_impact", "cumulative_impact",
    }


def test_peer_findings_name_their_cohort(l2):
    """A comparison whose basis the reviewer cannot see is not evidence."""
    seen = 0
    for hit in l2.hits:
        peer = json.loads(hit["evidence_json"]).get("peer_context")
        if not peer:
            continue
        seen += 1
        assert peer["cohort_key"] and peer["cohort_n"]
        assert set(peer) <= set(PEER_FIELDS) | {"employee_value"}
    assert seen, "no finding carried a peer comparison at all"


def test_salary_attributions_are_in_riyals(l2):
    """The point of the layer: the split a reviewer can take to a manager."""
    bundles = [json.loads(h["evidence_json"]) for h in l2.hits]
    attributed = [b for b in bundles if b.get("feature_attributions")]
    assert attributed
    for bundle in attributed:
        for item in bundle["feature_attributions"]:
            assert item["label_en"] and item["feature"]
            assert item["direction"] in ("increases", "reduces")
            assert isinstance(item["contribution"], (int, float))


def test_no_ml_jargon_reaches_the_reviewer(l2):
    for hit in l2.hits:
        for text in [hit["description"], *hit["recommended_actions"]]:
            found = [w for w in JARGON if w in text.lower()]
            assert not found, f"{hit['anomaly_code']}: {found} in {text[:80]!r}"


def test_layer_2_is_deterministic(con, policy, l2):
    """Two passes over one lake must find the same cases with the same wording."""
    again = run_peer(con, policy)
    assert again.by_code == l2.by_code
    assert [h["description"] for h in again.hits] == [
        h["description"] for h in l2.hits
    ]


def test_severities_come_from_the_pack(l2, policy):
    for hit in l2.hits:
        assert hit["severity"] == policy.peer_codes[hit["anomaly_code"]]["severity"]
